### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by insxa** [Yahav/whmcs-azuracast#1]
Hello can you make this modue for fossbilling/paymenter ? Its open-source billing system for hosting.

**Comment by Yahav** [comment]
Hmm, both of those are seem to not even reached v1 which might mean they will implement breaking changes.
Even if i'll be able to create a module for those i won't be able to maintain it so i rather leave this for someone else.
I suggest posting a Feature request at the official AzuraCast page:
https://features.azuracast.com/
